##' Function to build attribution dataframe from a query to the iDigBio API
##'
##' Exported.
##' @title Attribution dataframe of iDigBio records query
##' @param dat dataframe generated by idig_search method
##' @return a data frame
##' @author Kevin Love
##' @export


idig_build_attrib <- function(dat){
        dat$count <- 1
        datAgg <- aggregate(count ~ recordset, data = dat,sum)
        datAt <- attributes(dat)
        dx <- data.frame(stringsAsFactors = FALSE)
        for (i in seq(1,length(datAt$attribution))){
                if (datAt$attribution[[i]]$uuid %in% dat$recordset) {
                        collection <- datAt$attribution[[i]]$name
                        uuid <- datAt$attribution[[i]]$uuid
                        itemCount <- datAgg$count[datAgg$recordset == datAt$attribution[[i]]$uuid]
                        rows <- cbind(data.frame(collection,stringsAsFactors = FALSE),data.frame(uuid,stringsAsFactors = FALSE),data.frame(itemCount,stringsAsFactors = FALSE))
                        dx <- plyr::rbind.fill(dx,rows)
                }

        }
        dx
}
